// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msxgitulqwqkgzkobyow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zeGdpdHVscXdxa2d6a29ieW93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NTY0NjEsImV4cCI6MjA3NDMzMjQ2MX0.NBnFhoyfkAnwpsSK7pR6MzhdtzumjI0yyiOZt4LeEBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});